In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.datasets import make_blobs


C:\Users\SUYASH\AppData\Roaming\Python\Python311\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [2]:
def my_softmax(z):
    ez = np.exp(z)
    sm = ez/np.sum(ez)
    return(sm)

In [5]:
#Sample dataset
centers = [[-5,2],[-2,-2],[1,2],[5,-2]]
x_train, y_train = make_blobs(n_samples=2000, centers=centers, cluster_std=1.0, random_state=30)

The Obvious method

In [7]:
model = Sequential(
    [
        Dense(25, activation='relu'),
        Dense(15, activation='relu'),
        Dense(4, activation='softmax')
    ]
)

model.compile(
    loss = tf.keras.losses.SparseCategoricalCrossentropy(),
    optimizer = tf.keras.optimizers.Adam(0.001),
)

model.fit(
    x_train, y_train, epochs=10
)

Epoch 1/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.9360
Epoch 2/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3255
Epoch 3/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1511
Epoch 4/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0968
Epoch 5/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0746
Epoch 6/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0631
Epoch 7/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0561
Epoch 8/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0513
Epoch 9/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0466
Epoch 10/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0434


In [8]:
p_nonpreferred = model.predict(x_train)
print(p_nonpreferred[:2])
print("Larget value",np.max(p_nonpreferred), "smallest value",np.min(p_nonpreferred))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
[[3.0991342e-03 1.4337210e-03 9.6073347e-01 3.4733690e-02]
 [9.9722517e-01 2.6342594e-03 1.3785624e-04 2.6741516e-06]]
Larget value 0.9999982 smallest value 1.6295926e-11


Preferred Model

In [12]:
p_model = Sequential(
    [
        Dense(25, activation='relu'),
        Dense(15, activation='relu'),
        Dense(4, activation='linear')
    ]
)

p_model.compile(
    loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer = tf.keras.optimizers.Adam(0.001),
)

p_model.fit(
    x_train, y_train, epochs=10
)

Epoch 1/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.0337 
Epoch 2/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4101
Epoch 3/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1888
Epoch 4/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1057
Epoch 5/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0732
Epoch 6/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0592
Epoch 7/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0510
Epoch 8/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0459
Epoch 9/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0414
Epoch 10/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0380


In [13]:
p_preferred = p_model.predict(x_train)
print(f"two example output vectors:\n{p_preferred[:2]}")
print("largest value", np.max(p_preferred), "smallest values",np.min(p_preferred))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
two example output vectors:
[[-2.8315032  -1.3194939   3.7101798  -0.8052521 ]
 [ 5.2353225   0.47638223 -4.256678   -2.7099016 ]]
largest value 10.534926 smallest values -9.067416


In [14]:
sm_preferred = tf.nn.softmax(p_preferred).numpy()
print(f"two example output vectors:\n{sm_preferred[:2]}")
print("largest value",np.max(sm_preferred), "smallest value",np.min(sm_preferred))

two example output vectors:
[[1.4152796e-03 6.4194761e-03 9.8142952e-01 1.0735740e-02]
 [9.9107587e-01 8.4981704e-03 7.4779651e-05 3.5118833e-04]]
largest value 0.99999785 smallest value 1.3901982e-08


In [15]:
for i in range(5):
    print(f"{p_preferred[i]}, category:{np.argmax(p_preferred[i])}")

[-2.8315032 -1.3194939  3.7101798 -0.8052521], category:2
[ 5.2353225   0.47638223 -4.256678   -2.7099016 ], category:0
[ 3.7897205  0.7516443 -3.160897  -2.244096 ], category:0
[-2.2315478  4.1543365 -1.7362405 -0.9421856], category:1
[-0.5237207 -2.005963   4.8283763 -3.371816 ], category:2
